### ISSUE TITLE
HA mode for injector

### ISSUE THREAD

**Issue by martinhaus** [hashicorp/vault-helm#238]
Is there a specific reason why injector deployment is set to a single replica?
Wouldn't it be better to have multiple replicas with PDB specified? 

Right now when the cluster is scaling and injector pod gets rescheduled on a different node, other pods can have problems starting up since they won't be to load secrets while the injector is spawning.

**Comment by zystem** [comment]
Injector is critical component. But helm for it did not support "Node-Selectors", "Tolerations" and "Affinity"

**Comment by pajel** [comment]
Upvoting. Would be great to have the replicas of the "vault-agent-injector" deployment customisable. Thanks.

**Comment by gopisaba** [comment]
I had similar issue today, some of the pods tried to restart at the same which includes vault-agent-injector pod. Since the service was down at that time, the mutation webhook failed to inject the init container to the other pods. They all started crashing as they were unable to find the secrets. Once the vault-agent-injector service is up (after seconds), restarting other containers started working. 

`vault-agent-injector` is critical component and we must have multiple replicas, node-selector, tolerations and affinity.

**Comment by camilorivera** [comment]
Same, HA for the injector should be a priority

**Comment by drpebcak** [comment]
Definitely should be a priority. Causes all sort of weird issues when the injector pod is rescheduled at the same time as others.

**Comment by rcjames** [comment]
An explanation for why this is not configurable was offered in #331. This still seems like a crucial feature though, so hopefully the bug will be addressed soon.
https://github.com/hashicorp/vault-helm/issues/331#issuecomment-651279027

**Comment by mitchellmaler** [comment]
The way I got around this was using cert-manager and it's [CA Injector](https://cert-manager.io/docs/concepts/ca-injector/). This allowed cert manager to generate the cert for the webhook and also patch the MutatingWebhookConfiguration automatically with the cabundle. I would be curious if this could be an acceptable enhancement to the helm chart to allow using cert-manager and adding the annotation the the webhook config instead of recreating this functionality?

**Comment by orirawlings** [comment]
The way my team worked around this was to just block pod creation until the vault-agent-injector is available once again, since generally outages due to rescheduling the vault-agent-injector pod are quite brief. We did this by ensuring that we could configure the [`failurePolicy`](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#failure-policy) on the MutatingWebhookConfiguration. See #400 

Even if you have multiple replicas and a PDB, there are still scenarios where you might lose all your replicas at once, for example, due to the unexpected failure of multiple nodes (i.e. any event where PDB is not consulted). Instituting a `failurePolicy` is a good way to ensure that the API server isn't allowing any misconfigured pods to be created.

**Comment by tvoran** [comment]
Hi folks, in v0.9.0 we added support for multiple injector replicas, and some documentation describing the setup is going up in this PR: hashicorp/vault#10659

@mitchellmaler I like the idea of leveraging cert-manger for this too. At the very least I could see that setup being a nice addition to our website docs.

**Comment by MeijerM1** [comment]
Multiple replicas simply isn't enough to guarantee HA. The ability to configure PBD and Affinity (already possible) are necessary to make sure an injector is available at all times.

**Comment by tvoran** [comment]
@MeijerM1 Yep, agreed. A configurable PDB was added in https://github.com/hashicorp/vault-helm/pull/653 and will go out with the next release.

The multiple replica support was improved in [v0.16.0](https://github.com/hashicorp/vault-helm/blob/main/CHANGELOG.md#0160-september-16th-2021), and cert-manager support was improved in [v0.15.0](https://github.com/hashicorp/vault-helm/blob/main/CHANGELOG.md#0150-august-23rd-2021) with an example documented here: https://www.vaultproject.io/docs/platform/k8s/helm/examples/injector-tls-cert-manager

Closing for now. Thanks for all the input folks!
