### ISSUE TITLE
Scaling Pods results in zombie instances in Consul

### ISSUE THREAD

**Issue by Skaronator** [hashicorp/vault-helm#29]
When scaling down the Vault replicas it results in zombie instances in Consul. I'm not a kubernetes expert but seems like doing a `preStop` Lifecycle hook which does a `consul leave` command could do the trick.

Consul looks like this for me now:
![image](https://user-images.githubusercontent.com/2886913/63410149-eef44a80-c3f2-11e9-8646-d00baf31b1c8.png)

Is there a way to manually remove these instances manually? Or do they go away after a while.

**Comment by jasonodonnell** [comment]
Hi @Skaronator, thanks for bringing this to our attention!

Yes, I do believe this could be handled better.  I think a custom preStop is a good idea and will consider implementing something like this!

Leaving this issue open to track progress.

**Comment by jasonodonnell** [comment]
I've actually found the root cause of this @Skaronator.  For some reason the Vault pod is not receiving SIGTERM and after the grace period ends, Kubernetes sends SIGKILL.  This means Vault never gets the chance to deregister itself.

I'm adding the following to avoid this issue:
```
lifecycle:
  preStop:
    exec:
      command: ["/bin/sh","-c","kill -SIGTERM $(pidof vault)"]
```

Unfortunately I think the services will need to be cleaned up manually using `consul service deregister`

**Comment by Skaronator** [comment]
Cool thats great to hear!
