### ISSUE TITLE
Usage of  `vault-active` and `vault-standby` services ?

### ISSUE THREAD

**Issue by pamiel** [hashicorp/vault-helm#347]
Dear Community,

My understanding is that the `vault-active` and `vault-standby` services are directly related to the presence of the ingress or routes to access to Vault from outside of the Kubernetes cluster.
If using NodePort instead of ingress (or routes) to access to Vault from outside of the cluster, what is your advice regarding the service to be used: `vault` or `vault-active` ? (I guess that `vault-standby` is out of the race :P )

Indeed, as soon as the Vault clustering is in place, then we can contact whatever instance of Vault server (active or standby) and the requests will be processed (thanks to the forwarding mechanism between the standby servers and the active servers). So when NodePort is used, `vault-active` and `vault-standby` are somehow useless (and may even generate issues: see https://github.com/hashicorp/vault-helm/issues/344) and using the `vault` service is enough, isn't it?

And even considering now internal calls to Vault from within the Kubernetes cluster: again, the Vault clustering ensures that we can target whatever Vault server instance. So in this case as well, `vault-active` and `vault-standby` services look useless...

Sorry if my understanding is incorrect or if I missed one thing, but my feeling is here that the `vault-active` and `vault-standby` services are only used for Ingree and Routes, and are useless in any other case. If this feeling is correct, why creating these service in all these other use cases as it may generate some confusions.
Just adding a 
`{{- if or .Values.server.ingress.enabled .Values.server.route.enabled }}`
in the corresponding file would make it...

Of course I could provide the PR if you agree with my analysis.

**Comment by jasonodonnell** [comment]
@pamiel Thanks for your analysis.  Vault's forwarding mechanism works great in _most_ cases, but not all.

For example, in Vault Enterprise, setting up replication between Vault clusters requires direct communication with the active node in the cluster.  This means using a generic load balancer will not work (Vault is actually being changed to fix this, but not in yet).

There's also other optimizations that can be made by applications where requests can be directed directly to active/standby servers to avoid overhead of forwarding (such as write requests going directly to active).

Hope that clarifies, but when HA mode is enabled we'll be keeping the active/standby services since use cases go beyond ingress/routes.
