### ISSUE TITLE
Support service topology

### ISSUE THREAD

**Issue by gnarea** [hashicorp/vault-helm#424]
**Is your feature request related to a problem? Please describe.**

If you have a HA deployment spanning multiple availability zones, your pods may be connecting to a Vault instance in another AZ.

**Describe the solution you'd like**

Use service topology: https://kubernetes.io/docs/concepts/services-networking/service-topology/

**Describe alternatives you've considered**

None

**Additional context**

If it's something you're open to, I can put a PR together.

**Comment by jasonodonnell** [comment]
Hi @gnarea, if you want to open a PR, that would be awesome. You can tag me if you do so! If not we'll track this internally and get something in.

**Comment by tvoran** [comment]
Thanks, though it looks like https://kubernetes.io/docs/concepts/services-networking/service-topology/ is now deprecated, and was replaced with [topology aware hints](https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/). And it looks like that topology aware hints just requires an annotation on the service? Since that's configurable in the chart, I'm going to close this for now.
