### ISSUE TITLE
Add label to vault active service for prometheus ServiceMonitor

### ISSUE THREAD

**Issue by hamza3202** [hashicorp/vault-helm#467]
**Is your feature request related to a problem? Please describe.**
I would like to scrape prometheus metrics from vault(HA mode) using `vault-active` service and prometheus ServiceMonitor. The service monitor allows to select a service based on its labels, however, the `active`, `standy` and other services created by helm have the same labels and hence a selection is not possible.

**Describe the solution you'd like**
Add a default label like `vault: active` to vault-active service or provide functionality to specify additional labels for vault-active service

**Describe alternatives you've considered**

**Additional context**

I am willing to create a PR if the approach can be finalised i.e add default label or provide additional labels

**Comment by hamza3202** [comment]
@jasonodonnell Any feedback on this?

**Comment by thomasmRavn** [comment]
If you don't use Istio you can probably work around this issue by using prometheus' podmonitors instead.

However istio has trouble working with podmonitors since they go via IP and istio uses service name for a lot of its routing. So if we can get a label on the service and use service monitors that would be amazing for us.

**Comment by tvoran** [comment]
Thanks, a `vault-active: true` label was added in #772
