### ISSUE TITLE
vault-injector: add allowPrivilegeEscalation: false in injector.leaderElector configuration

### ISSUE THREAD

**Issue by mickael1026** [hashicorp/vault-helm#544]
**Is your feature request related to a problem? Please describe.**
Add securitycontext to follow security model of our kubernetes deployment.

**Describe the solution you'd like**
Add the securitycontext "allowPrivilegeEscalation: false" in the container definition of leader-elector container.

**Additional context**
We have some policy enforced in our kubernetes cluster, one of them enforce us to set allowPrivilegeEscalation: false in all pods deployment.

**Comment by tvoran** [comment]
Hi @mickael1026, as of vault-helm [0.16.0](https://github.com/hashicorp/vault-helm/blob/master/CHANGELOG.md#0160-september-16th-2021) the chart no longer deploys a separate leader-elector container by default, since vault-k8s [0.13.0](https://github.com/hashicorp/vault-k8s/blob/master/CHANGELOG.md#0130-september-15-2021) no longer requires one. Closing this for now.
