### ISSUE TITLE
RFE: Ability to restart vault on configmap change

### ISSUE THREAD

**Issue by TJM** [hashicorp/vault-helm#748]
**Is your feature request related to a problem? Please describe.**

When I change the configuration, such as to add "plugin_directory" to the config, it does not "notify" the pods to restart.

**Describe the solution you'd like**

A common way to handle that is to use a sha256sum of contents of the configmap as an annotation to the pod. This allows for a simple "notification" that the pods need to restart.

**Describe alternatives you've considered**

Some sort of post-upgrade hook?

**Additional context**

https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

**Comment by tvoran** [comment]
Hi @TJM, indeed Vault server is deployed as a statefulset in this chart, but with a default [updateStrategy of OnDelete](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies). This is intentional as detailed in the [Upgrading Vault on Kubernetes section](https://www.vaultproject.io/docs/platform/k8s/helm/run#upgrading-vault-on-kubernetes) of the docs.

You're free to change that by setting `server.strategyType` in the chart values.

**Comment by agill17** [comment]
I think this is still a nice thing to have, while leaving the default updateStrategy to "onDelete".

If the hash of configmap changes, then the pod-template label will change too. Also the status.updateRevision will no longer match status.currentRevision.
One could then use that status change to identify whether to roll/not-roll vault pods in safe manner.

In server-statefulset.yaml, we would change this
```
 {{- toYaml .Values.server.extraLabels | nindent 8 -}}
```

To

```
{{- tpl (toYaml .Values.server.extraLabels) .  | nindent 8 -}}
```

**Comment by tvoran** [comment]
Good point, @agill17, re-opening this.
