### ISSUE TITLE
[QUESTION] Kubernetes supported version

### ISSUE THREAD

**Issue by EvertonSA** [hashicorp/vault-helm#799]
Hi colleagues, 

The README.md mentions the following requirements:

```
The versions required are:

Helm 3.6+
Kubernetes 1.16+ - This is the earliest version of Kubernetes tested. It is possible that this chart works with earlier versions but it is untested.
```

Is it safe to assume it works on version 1.22, 1.23, 1.24 and 1.25 are supported?

**Comment by tvoran** [comment]
Hi @EvertonSA, yes, these are the k8s versions that the chart is tested with currently: https://github.com/hashicorp/vault-helm/blob/main/.github/workflows/acceptance.yaml#L10

The chart and our tests still work with k8s 1.16 which is why that version is still in the list and the readme, though we're not really making an effort to support it, it just so happens to still work, if that makes sense.

**Comment by EvertonSA** [comment]
@tvoran that is very great news, thanks a lot, closing this
