### ISSUE TITLE
Update helm chart to AppVersion v1.13.0

### ISSUE THREAD

**Issue by jordanfelle** [hashicorp/vault-helm#856]
When can we expect Vault 1.13 to be added to the helm chart? I also see that 1.12 minor versions were never added, is that normal and is it expected we version those ourselves?

**Comment by tvoran** [comment]
Hi @jordanfelle, yes [we recommend](https://developer.hashicorp.com/vault/docs/platform/k8s/helm/configuration#tag-2) setting the vault image version in your deployments and not relying on the default in the chart.

Since Vault is not tightly coupled with the chart, we generally do not update the default Vault version in the chart for every patch release. That being said, we'll try to get a new release with a 1.13.x default out soon!
